### ISSUE TITLE
Error in submit data

### ISSUE THREAD

**Issue by anuragp2018** [ashna111/multimodal-image-fusion-to-detect-brain-tumors#21]
hey i am trying to submit data it show error 
Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\asus\Downloads\multimodal-image-fusion-to-detect-brain-tumors-master\multimodal-image-fusion-to-detect-brain-tumors-master\app.py", line 276, in register
    mriCoord=convertToIntList(request.form['mriCoord'])
  File "c:\Users\asus\Downloads\multimodal-image-fusion-to-detect-brain-tumors-master\multimodal-image-fusion-to-detect-brain-tumors-master\app.py", line 30, in convertToIntList
    x.append(int(i,10))
ValueError: invalid literal for int() with base 10: ''

**Comment by 2567245306** [comment]
have you overcome it?how?
